// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Malone_Bulkley_CSU_dotNET.Models;
[Table("budget_line")]
public partial class budget_line
{
    [Key]
    public int? category_id { get; set; }

    public string? category_name { get; set; }

    public int? year { get; set; }

    public int? month { get; set; }

    public decimal? budgeted_amount { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? actual_amount { get; set; }
}