// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Malone_Bulkley_CSU_dotNET.Models;

[Table("expense_income")]
public partial class expense_income
{
    [Key]
    public int charge_id { get; set; }

    public int? user_id { get; set; }

    public int? month_id { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? income_amount { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? expense_amount { get; set; }
}