// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Malone_Bulkley_CSU_dotNET.Models;

public partial class Team106DBContext : DbContext
{
    public Team106DBContext(DbContextOptions<Team106DBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<budget_line> budget_lines { get; set; }

    public virtual DbSet<category> categories { get; set; }

    public virtual DbSet<expense_income> expense_incomes { get; set; }

    public virtual DbSet<user> users { get; set; }

    public virtual DbSet<user_budget> user_budgets { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<budget_line>(entity =>
        {
            entity.HasKey(e => e.expense_line).HasName("PK__budget_l__557DBE0BA68AD746");
        });

        modelBuilder.Entity<category>(entity =>
        {
            entity.HasKey(e => e.category_id).HasName("PK__category__D54EE9B43B6AC2E5");
        });

        modelBuilder.Entity<expense_income>(entity =>
        {
            entity.HasKey(e => e.charge_id).HasName("PK__expense___F3F52EBC49824D6D");
        });

        modelBuilder.Entity<user>(entity =>
        {
            entity.HasKey(e => e.user_id).HasName("PK__users__B9BE370FD3FAF2DD");
        });

        modelBuilder.Entity<user_budget>(entity =>
        {
            entity.HasKey(e => e.budget_id).HasName("PK__user_bud__3A655C1476055849");

            entity.Property(e => e.created_at)
                .IsRowVersion()
                .IsConcurrencyToken();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}