// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Malone_Bulkley_CSU_dotNET.Models;

[Table("user_budget")]
public partial class user_budget
{
    [Key]
    public int budget_id { get; set; }

    public int? user_id { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? budget_amount { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? month_difference { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? actual_amount { get; set; }


    [Required]
    public byte[] created_at { get; set; }
}