// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Malone_Bulkley_CSU_dotNET.Models;

public partial class user
{
    [Key]
    public int user_id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string username { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string email { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string password { get; set; }
}